# Generated by Django 3.0.7 on 2021-02-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicinfo',
            name='address_info',
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=542004, unique=True),
        ),
        migrations.DeleteModel(
            name='StudentAddressInfo',
        ),
    ]
