# Generated by Django 3.0.7 on 2021-02-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20210203_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicinfo',
            name='previous_academic_info',
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=724458, unique=True),
        ),
        migrations.DeleteModel(
            name='PreviousAcademicInfo',
        ),
    ]
