# Generated by Django 3.0.7 on 2021-02-03 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('student', '0003_auto_20210203_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousAcademicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.CharField(max_length=100)),
                ('name_of_exam', models.CharField(max_length=100)),
                ('group', models.CharField(max_length=45)),
                ('gpa', models.CharField(max_length=10)),
                ('board_roll', models.IntegerField()),
                ('passing_year', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='guardian_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.GuardianInfo'),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=544272, unique=True),
        ),
        migrations.CreateModel(
            name='StudentAddressInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village', models.TextField()),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.District')),
                ('union', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.Union')),
                ('upazilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.Upazilla')),
            ],
        ),
        migrations.AddField(
            model_name='academicinfo',
            name='address_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.StudentAddressInfo'),
        ),
        migrations.AddField(
            model_name='academicinfo',
            name='previous_academic_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.PreviousAcademicInfo'),
        ),
    ]
